# Generated by Django 4.2.4 on 2023-08-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossastore',
            name='product_link',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='fossastore',
            table='fossa_store',
        ),
    ]
